"""Generate the sample Q&A deliverable by running the real assistant."""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from mf_rag.config import DELIVERABLES_DIR
from mf_rag.embed_store import load_chunks
from mf_rag.pipeline import get_assistant
from mf_rag.sources import DISCLAIMER

QUERIES = [
    ("What is the expense ratio of HDFC Large Cap Fund?", "expense ratio (fact)"),
    ("What is the exit load of HDFC ELSS Tax Saver Fund?", "exit load (fact)"),
    ("Is there a lock-in period on HDFC ELSS Tax Saver Fund?", "ELSS lock-in (fact)"),
    ("What is the minimum SIP for HDFC Balanced Advantage Fund?", "minimum SIP (fact)"),
    ("What is the benchmark of HDFC Balanced Advantage Fund?", "benchmark (fact)"),
    ("What is the riskometer level of HDFC Flexi Cap Fund?", "riskometer (fact)"),
    ("Who manages HDFC Large Cap Fund?", "fund manager (fact)"),
    ("How do I download my capital gains statement?", "statement guidance"),
    ("Should I buy HDFC Small Cap Fund?", "advice refusal"),
    ("My PAN is ABCDE1234F, check my returns", "PII refusal"),
]


def main() -> int:
    DELIVERABLES_DIR.mkdir(parents=True, exist_ok=True)
    assistant = get_assistant()
    rows = []
    for question, topic in QUERIES:
        answer = assistant.ask(question)
        rows.append(
            {
                "question": question,
                "topic": topic,
                "answer": answer.text,
                "citation": answer.primary_citation,
                "last_updated": answer.retrieved_at,
                "intent": answer.intent,
                "kind": answer.kind,
                "refused": answer.refused,
            }
        )

    chunks = load_chunks()
    latest = max((c.retrieved_at for c in chunks), default="")

    lines = [
        "# Sample Q&A - HDFC Mutual Fund facts assistant",
        "",
        f"Generated by `scripts/make_sample_qa.py` against the built index ({len(chunks)} chunks).",
        f"Corpus last refreshed: **{latest}**",
        "",
        f"> {DISCLAIMER}",
        "",
        "Every answer is extractive: the sentences are copied from the retrieved chunk on the cited",
        "page. Nothing is generated, summarised or inferred by a language model. Every row carries",
        "exactly one source link; the PII row cites the privacy policy because no fund page was",
        "consulted, and is the only row with no timestamp.",
        "",
        "---",
        "",
    ]
    for index, row in enumerate(rows, start=1):
        lines += [
            f"### {index}. {row['question']}",
            "",
            f"**Topic:** {row['topic']}  ",
            f"**Answer:** {row['answer']}  ",
            f"**Source:** {row['citation']}  ",
            f"**Last updated from sources:** {row['last_updated'] or 'n/a (no source consulted)'}  ",
            f"**Route:** intent=`{row['intent']}` kind=`{row['kind']}` refused=`{row['refused']}`",
            "",
        ]

    (DELIVERABLES_DIR / "SAMPLE_QA.md").write_text("\n".join(lines), encoding="utf-8")
    (DELIVERABLES_DIR / "SAMPLE_QA.json").write_text(
        json.dumps(rows, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(f"wrote {len(rows)} Q&A pairs to {DELIVERABLES_DIR}")
    for row in rows:
        print(f"  [{row['kind']:>20}] {row['question'][:60]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
